services:
    server:
        container_name: signalize-web
        build: .
        working_dir: /var/www
        volumes:
            - ./.:/var/www:delegated
        ports:
            - 4321:4321
        environment:
            ENV: dev
        tty: true
